version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: node_api
    restart: always
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=admin"
    volumes:
      - ./gameScript.sql:/docker-entrypoint-initdb.d/gameScript.sql
  app:
    build: .
    command: npm start
    ports:
      - '8087:8087'
    volumes:
      - .:/app
    depends_on:
      - db
